### PR TITLE
Fix for "More than one instance of bitcore-lib found."

### PR DESCRIPTION
**Pull request by Srirangan**
I ran into this issue again with 2.5.6. Here's a fix:

```
Uncaught Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (.../node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (.../node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Object.<anonymous> (.../node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:71:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

### CODE REVIEW

**Comment by christianlundkvist** [comment]
This doesn't work for me. When I remove the `bitcore-lib` reference there package `bitcore-mnemonic` puts its dependency in `bitcode-mnemonic/node_modules/bitcore-lib` and when I do `require('bitcore-lib')` it can't actually find it. Manually removing the folder `bitcode-mnemonic/node_modules/bitcore-lib` works but that's a bit too hacky I feel. I'm on node 8.7.0

**Comment by Srirangan** [comment]
@christianlundkvist builds and tests pass for me on this branch. Can you confirm what exactly doesn't work for you?

**Comment by christianlundkvist** [comment]
@Srirangan I'm getting the error `Error: Cannot find module 'bitcore-lib'` when I run `npm run test`.

**Comment by christianlundkvist** [comment]
@Srirangan Ah there was a `package-lock.json` file floating around which I removed. That seems to have fixed it! Now `npm run test` works as expected.

**Comment by Srirangan** [comment]
@christianlundkvist Nice, then can we merge this please ... I would like to update my package.json to stop depending on srirangan/eth-lightwallet :)

**Comment by christianlundkvist** [comment]
@Srirangan I'm going to try to merge in the big cleanup v3.0.0 today which will include this fix.

**Comment by achadha235** [comment]
shouldn't `bitcore-lib ^0.15` be at least a peerDependency given that its referenced in the source? I feel the correct fix for this problem is to match the version of `bitcore-lib` that is in the currently chosen version of `bitcore-mnemonic` and / or make `bitcore-lib` a peerDependency...Removing it completely will lead to very confusing errors should the implicit inclusion of `bitcore-lib` through `bitcore-mnemonic` ever fail. My vote is letting the consumer decide which version they want to use by making it a peer / dev Dependency.

**Comment by junderw** [comment]
this can be fixed by removing the ^ in front of bitcore-mnemonic.

We have to fork now because of this. Hope something is done soon. (bitcore can burn their versionguard)

**Comment by christianlundkvist** [comment]
This has now been fixed in https://github.com/ConsenSys/eth-lightwallet/pull/166. For a temporary fix you may also use the branch `srirangan/eth-lightwallet` until you are upgraded to v3.0.0.

**Pull request closed without merging**
